### ISSUE TITLE
Preferowany termin i godziny spotkania

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Mlodzi_w_IT#1]
# Styczeń 2019
Na pewno chciałbym zrealizować ten podcast w styczniu jednego dnia.
Preferowany okres to **I połowa stycznia** pomiędzy (06 - 17 stycznia)
Spotykamy się w grupach więc np. grupa_1 09:00, grupa_2 10:30, grupa_3 12:00.
Zdaję sobie sprawę, że pracujecie, studiujecie i wciągu dnia może być ciężko wyskoczyć na nagranie dlatego godziny postaramy się dogadać.
Wpiszcie w komentarzu swoje preferencję. Jeśli ktoś już teraz wie, że wyjeżdża w styczniu to niech również to zaznaczy.

**Comment by MastalerzKamil** [comment]
Mi teraz uczelnia odchodzi więc właściwie z rana nawet lepiej dla mnie. Jeśli chodzi o termin to może początek stycznia?

**Comment by Snooking** [comment]
Mi też uczelnia odchodzi, a z pracy mogę się urwać na dwie/trzy godzinki, więc godzina dowolna :) W styczniu nigdzie nie wyjeżdżam, więc dzień również dowolny

**Comment by krichert** [comment]
Hej :) jeśli chodzi o mnie to dni z tego zakresu co napisałes to nie pasują: 6, 11, 12, 16, 17. Co do godizny to jak będę znać termin to będzie mi łatawiej powiedzieć (nie wiem czy nie będę miał jakiegoś ważnego spotkania), ale ogólnie to godzinny poranne dla mnie jak najbardziej ok.

**Comment by GKotfis** [comment]
Czekamy jeszcze na Ewe, która się zgłosiła do projektu ale nie zostawiła informacji. 
Mam otwarty jeszcze nabór na jedną, dwie osoby.

**Comment by etusien** [comment]
Hej, 
Jestem dostępna przez cały styczeń. I oczywiście elastyczny grafik w pracy, więc będę mogła dostosować się do terminu. :D

**Comment by GKotfis** [comment]
Co powiecie na któryś piątek?
17.01 (@krichert nie pasuje chyba, że coś uległo zmianie)
24.01
31.01

**Comment by krichert** [comment]
Hej :) zgadza się, ja 17.01 nie moge, ale pozostałe dni dla mnie super :D

**Comment by annrogal** [comment]
Mi pasuje każdy dzień od poniedziałku do piątku. Jeśli chodzi o godziny to dopiero po 16 😉

**Comment by etusien** [comment]
Dla mnie termin są ok. :)

**Comment by GKotfis** [comment]
Moja propozycja **24.01.**
Miejsce: **Inkubator Starter** (Gdańsk Przymorze-Uniwersytet)
3 sloty:
**12:00**: @krichert @Ewa21 
**14:00**: @MastalerzKamil Aleksander Kozyra
**16:30**: @annrogal @Snooking

Jestem elastyczny więc możemy te godziny poprzesuwać. Jeśli byłaby potrzeba zrobić jeden slot z rana np. na 09:00

**Comment by etusien** [comment]
Ok. @krichert  pisałeś, że wolisz rano, więc jak coś to możemy na 9:00 ;)

**Comment by annrogal** [comment]
Mi termin pasuje 😀

**Comment by Nezale** [comment]
24.01 jak najbardziej pasuje 😃

**Comment by Snooking** [comment]
Mi również pasuje :)

**Comment by MastalerzKamil** [comment]
24.01 pasuje mi:)

**Comment by krichert** [comment]
Hej ;) tak rano dla mnie lepiej, ale domyslam sie, ze @GKotfis woli robic jedno po drugiem, a dla mnie 12 spoko, wiec juz nie zmieniajmy :)

**Comment by GKotfis** [comment]
Taki miałem zamysł żeby zarezerwować salę od 12:00 - 18:00 i spotykać się z wami po kolei. Piątek ma cały wolny więc jestem elastyczny.
@Ewa21 @krichert zostajemy przy 12:00 czy przesuwamy na 09:00?

**Comment by etusien** [comment]
Dla mnie 12:00 jest ok

**Comment by krichert** [comment]
Tak, zostanmy przy 12 :)

**Comment by GKotfis** [comment]
No to mamy klepnięty termin **24.01**
Rezerwuję salę!
